### ISSUE TITLE
Tests won't run unless development setup (pip install) is used

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#16] opened 2017-11-17 12:34 UTC
Is this desirable?

Current output from running pytest is:

```
[michael@laptop cellmlmanip]$ ls
total 28
drwxrwxr-x 3 michael michael 4096 Nov 17 12:22 cellmlmanip
-rw-rw-r-- 1 michael michael 1515 Nov 17 12:22 LICENSE
-rw-rw-r-- 1 michael michael 1461 Nov 17 12:22 README.md
drwxrwxr-x 2 michael michael 4096 Nov 17 12:22 requirements
-rw-rw-r-- 1 michael michael  473 Nov 17 12:22 setup.py
drwxrwxr-x 3 michael michael 4096 Nov 17 12:28 tests
-rw-rw-r-- 1 michael michael   51 Nov 17 12:22 tox.ini
[michael@laptop cellmlmanip]$ ls cellmlmanip/
total 4
-rw-rw-r-- 1 michael michael    0 Nov 17 12:22 __init__.py
drwxrwxr-x 2 michael michael 4096 Nov 17 12:22 mathml2sympy
[michael@laptop cellmlmanip]$ pytest-3
=================================== test session starts ===================================
platform linux -- Python 3.6.2, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/michael/dev/weblab/cellmlmanip, inifile:
collected 0 items / 1 errors                                                               

========================================= ERRORS ==========================================
_______________________ ERROR collecting tests/test_mathml2sympy.py _______________________
ImportError while importing test module '/home/michael/dev/weblab/cellmlmanip/tests/test_mathml2sympy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_mathml2sympy.py:6: in <module>
    from cellmlmanip import mathml2sympy
E   ModuleNotFoundError: No module named 'cellmlmanip'
!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!
================================= 1 error in 0.52 seconds =================================
```

**Comment by MichaelClerx** [comment] 2017-11-17 12:35
For one thing it wouldn't test the code in the repo if you forgot to add `-e` to your `pip install`

**Comment by jonc125** [comment] 2017-11-17 13:08
I'd say this is desirable. You can get subtle bugs if you're not testing an installed package. (Even installed with `-e` can let some things work that wouldn't if the package was installed normally. But catching those is what travis is for :) )

**Comment by MichaelClerx** [comment] 2017-11-17 13:44
So can travis be set up to pip install the package before testing? Is that what we're doing?

**Comment by MichaelClerx** [comment] 2017-11-17 13:53
Thinking this true I can follow your logic from start to finish but the end result is just so weird! If you have code + a test, surely the test should test the code :-)

**Comment by jonc125** [comment] 2018-01-22 13:03
Closing as this is the intended behaviour.

**Closed by jonc125** 2018-01-22 13:03 UTC
