### ISSUE TITLE
Make sure initial values are exclusively for state variables

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#205] opened 2020-01-29 12:03 UTC
CellML allows them to be used to define constants as well, but in libcellml I think we want them only for state variables.
So, after parsing, initial values should only be set for state variables and errors should be raised if they're used in a different way

**Comment by jonc125** [comment] 2020-01-29 12:13
Duplicate of #201.

**Closed by jonc125** 2020-01-29 12:13 UTC
